version: "3"

services:
  db:
    container_name: db
    build: ./database
    restart: always  
    env-file: .env  
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
    - node-api-service

  server:
    container_name: server
    build:
      context: .
      dockerfile: docker/back/Dockerfile
    env-file: .env
    networks:
    - node-api-service  
networks:
  node-api-service:    
