version: "3"

services:
  db:
    container_name: db
    build: 
      context: .
      dockerfile: docker/db/Dockerfile
    env-file: .env  
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
    - node-api-service

  server:
    container_name: server
    build:
      context: .
      dockerfile: docker/back/Dockerfile
    env-file: .env
    networks:
    - node-api-service  
networks:
  node-api-service:    
