version: '3'

services:
  db:
    container_name: db
    build: ./database
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - node-api-service

  server:
    container_name: server
    build:
      context: .
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/server
      - /server/node_modules
    networks:
      - node-api-service
    tty: true

volumes:
  postgres_data:

networks:
  node-api-service:
    driver: bridge
